<h1 align=center style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
    مرتب‌سازی
</font>
</h1>

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc"><a href="https://numpy.org/doc/2.1/reference/routines.sort.html" target="_blank" style="color:#0099cc">🔗</a>(Sorting) مرتب‌سازی در نامپای
    </font>
</h2>

In [1]:
import numpy as np

np.random.seed(42)

In [2]:
arr = np.array([5, 2, 3, 4, 1])
print('Sorted Array:', np.sort(arr))
print('Original Array:', arr)

Sorted Array: [1 2 3 4 5]
Original Array: [5 2 3 4 1]


In [10]:
arr = np.array([5, 2, 3, 4, 1])

arr.sort()
print(arr)

[1 2 3 4 5]


In [4]:
arr = np.array([5, 2, 3, 4, 1])
idx = np.argsort(arr)
print(idx)

[4 1 2 3 0]


In [5]:
arr[idx]

array([1, 2, 3, 4, 5])

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">مرتب‌سازی در راستای محورها
    </font>
</h2>

In [6]:
arr2d = np.random.randint(0, 10, (4, 5))
print(arr2d)

[[6 3 7 4 6]
 [9 2 6 7 4]
 [3 7 7 2 5]
 [4 1 7 5 1]]


In [7]:
np.sort(arr2d, axis=0)

array([[3, 1, 6, 2, 1],
       [4, 2, 7, 4, 4],
       [6, 3, 7, 5, 5],
       [9, 7, 7, 7, 6]], dtype=int32)

In [8]:
np.sort(arr2d, axis=1)

array([[3, 4, 6, 6, 7],
       [2, 4, 6, 7, 9],
       [2, 3, 5, 7, 7],
       [1, 1, 4, 5, 7]], dtype=int32)

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">پارتیشن‌سازی
    </font>
</h2>

In [9]:
np.partition(arr2d, 2, axis=1)

array([[3, 4, 6, 6, 7],
       [2, 4, 6, 7, 9],
       [2, 3, 5, 7, 7],
       [1, 1, 4, 5, 7]], dtype=int32)