<h1 align=center style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
    آشنایی با کتابخانه نامپای (۲)
</font>
</h1>

In [3]:
import numpy as np 
np.random.seed(1400) 
#این کار باعث می‌شود که اعداد تصادفی تولید شده در هر بار اجرای کد یکسان باشند

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc"><a href="https://numpy.org/doc/stable/user/basics.indexing.html#basic-indexing" target="_blank" style="color:#0099cc">🔗</a>(Indexing) نمایه سازی
    </font>
</h2>

In [4]:
a = np.array([0, 1, 2, 3])
print(a)
print('a[0] =', a[0])
print('a[2] =', a[2])
print('a[-1] =', a[-1])

[0 1 2 3]
a[0] = 0
a[2] = 2
a[-1] = 3


In [5]:
a = np.random.randint(0, 10, (3, 5))
print(a)
print('a[2, 3] =', a[2, 3])

[[5 1 7 8 5]
 [8 1 8 3 8]
 [9 8 4 1 4]]
a[2, 3] = 1


In [6]:
a[2, 3] = 10
print('a[2, 3] =', a[2, 3])

a[2, 3] = 10


In [7]:
a[2, 3] = 3.14
print('a[2, 3] =', a[2, 3])

a[2, 3] = 3


<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc"><a href="https://numpy.org/doc/stable/user/basics.indexing.html#slicing-and-striding" target="_blank" style="color:#0099cc">🔗</a>(Slicing) برش
    </font>
</h2>

In [8]:
a = np.array([0, 1, 2, 3, 4])
print(a[:3])
print(a[2:4])
print(a[1:5:2])
print(a[::-1])

[0 1 2]
[2 3]
[1 3]
[4 3 2 1 0]


In [9]:
a = np.array([[0, 1, 2],
              [3, 4, 5],
              [6, 7, 8],
              [9, 10, 11]])
print('a[:2, 1:]= ',a[:2, 1:])
print('a[1:3, ::2]= ',a[1:3, ::2])

a[:2, 1:]=  [[1 2]
 [4 5]]
a[1:3, ::2]=  [[3 5]
 [6 8]]


In [10]:
print(a[:2, 1])
print(a[2, :])
print(a[:, 1])
print(a[2])

[1 4]
[6 7 8]
[ 1  4  7 10]
[6 7 8]


In [11]:
a = np.array([[0, 1, 2],
              [3, 4, 5],
              [6, 7, 8]])
sub_a = a[1:3, 1:]
sub_a[0, 0] = 10
print(a)

[[ 0  1  2]
 [ 3 10  5]
 [ 6  7  8]]


In [12]:
a = np.array([[0, 1, 2],
              [3, 4, 5],
              [6, 7, 8]])
sub_copy_a = a[2:4, 1:].copy()
sub_copy_a[0, 0] = 10
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">(Reshaping) بازآرایی
    </font>
</h2>

In [13]:
a = np.arange(16)
print(a)
print(a.reshape(4, 4))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [14]:
a = np.array([1, 2, 3])
print(a.reshape(3, 1))
print(a.reshape(1, 3))

[[1]
 [2]
 [3]]
[[1 2 3]]


In [15]:
a = np.arange(12)
print(a.reshape(2, -1, 3))

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">توابع عمومی
    </font>
</h2>

In [18]:
a = np.array([0, 1, 2, 3])
b = np.array([-2, 10, 1, 5])
print('a + b =', np.add(a, b)) 
print('a + b =', a + b) # است a + b معادل np.add(a, b)

a + b = [-2 11  3  8]
a + b = [-2 11  3  8]


In [19]:
print('a - b =', np.subtract(a, b)) 
print('a - b =', a - b) # است a - b معادل np.subtract(a, b)

a - b = [ 2 -9  1 -2]
a - b = [ 2 -9  1 -2]


In [20]:
print('a * b =', np.multiply(a, b)) 
print('a * b =', a * b) # است a * b معادل np.multiply(a, b)

a * b = [ 0 10  2 15]
a * b = [ 0 10  2 15]


In [21]:
print('a / b =', np.divide(a, b)) 
print('a / b =', a / b) # است a / b معادل np.divide(a, b)

a / b = [-0.   0.1  2.   0.6]
a / b = [-0.   0.1  2.   0.6]


In [22]:
a = np.random.randint(0, 11, 5) # آرایه‌ای شامل 5 عدد تصادفی در بازه 0 تا 10
b = np.random.randint(-10, 11, 5) # آرایه‌ای شامل 5 عدد تصادفی در بازه 10- تا 10
print('a =', a)
print('b =', b)

a = [8 0 7 3 0]
b = [ 1  4 -4 -3 -6]


In [23]:
print('absolute values of b =', np.abs(b)) 

absolute values of b = [1 4 4 3 6]


In [24]:
print('square values of a =', np.square(a)) 

square values of a = [64  0 49  9  0]


In [25]:
np.seterr(invalid="ignore") # خطای ناشی از عملیات غیرمجاز را نادیده می‌گیرد
a = np.array([1 , 2 , -3 , 4, -5])
print('a = ', a)
print('isnan results for a =', np.isnan(a))
print('sqrt(a) = ', np.sqrt(a))
print('isnan resultes for sqrt(a) =', np.isnan(np.sqrt(a)))

a =  [ 1  2 -3  4 -5]
isnan results for a = [False False False False False]
sqrt(a) =  [1.         1.41421356        nan 2.                nan]
isnan resultes for sqrt(a) = [False False  True False  True]
