<h1 align=center style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
    جبر خطی
</font>
</h1>

In [1]:
import numpy as np

row_vector = np.array([1, 2, 3, 4])
row_vector

array([1, 2, 3, 4])

In [2]:
column_vector = row_vector.reshape(-1, 1)
# or row_vector[:, np.newaxis]
# or row_vector[:, None]
column_vector

array([[1],
       [2],
       [3],
       [4]])

In [3]:
matrix = np.array([[1, 2, 3, 4], 
                   [5, 6, 7, 8]])
matrix

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [4]:
a = np.array([1, 1, 2])
b = np.array([50, 75, 16])
np.dot(a, b)

157

In [5]:
a = np.array([[1, 1, 2],
              [3, 3, 3]])
b = np.array([[50], [75], [16]])
np.matmul(a, b)

array([[157],
       [423]])

In [6]:
a = np.array([[1, 1, 2],
              [3, 3, 3]])
b = np.array([[50], [75], [16]])
a @ b

array([[157],
       [423]])

In [7]:
import numpy as np

A = np.array([[30, 120, 205],
              [2, 25, 4],
              [5, 0, 1]])

B = np.array([800, 50, 15])

servings = np.linalg.solve(A, B)

print("Recommended servings per day:")
print("Broccoli (X):", servings[0])
print("Chicken (Y):", servings[1])
print("Rice (Z):", servings[2])


Recommended servings per day:
Broccoli (X): 2.4510235527184703
Chicken (Y): 1.3647369579572968
Rice (Z): 2.7448822364076597
