<h1 align=center style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
    آشنایی با کتابخانه نامپای (۱)
</font>
</h1>

In [ ]:
import numpy as np # عموما به طور قراردادی از کتابخانهٔ نامپای به این شکل استفاده می‌شود
np.__version__ 

In [5]:
np.array([1, 2, 3]) #آرایه‌ی یک بعدی شامل ۳ عدد

array([1, 2, 3])

In [7]:
np.array([[1, 2], # آرایه‌ی دو بعدی ۲*۳ شامل ۶ عدد
         [3, 4],
         [5, 6]])

array([[1, 2],
       [3, 4],
       [5, 6]])

In [8]:
np.array([[['000', '001'], ['010', '011']],# آرایه‌ی سه بعدی ۲*۲*۲ شامل ۸ رشته
          [['100', '101'], ['110', '111']]])
#dtype نوع خانه‌های آرایه‌ی را نشان می‌دهد  
#<U3 یعنی نوع این آرایه رشته یونی‌کد ۳ حرفی است 

array([[['000', '001'],
        ['010', '011']],

       [['100', '101'],
        ['110', '111']]], dtype='<U3')

In [9]:
np.zeros(3) # آرایه‌ی یک بعدی شامل ۳ عدد حقیقی برابر صفر

array([0., 0., 0.])

In [10]:
np.ones((2, 3))# آرایه‌‌ی دو بعدی ۳*۲ شامل ۶ عدد حقیقی برابر یک

array([[1., 1., 1.],
       [1., 1., 1.]])

In [11]:
np.full((3, 2), '#')# آرایه‌ی دو بعدی ۲*۳ شامل ۶ رشته متنی '#' یکسان

array([['#', '#'],
       ['#', '#'],
       ['#', '#']], dtype='<U1')

In [12]:
np.arange(0, 15, 4)# آرایه‌ی یک بعدی شامل اعداد صحیح پیش از ۱۵ با شروع از ۰ و با فاصله ۴

array([ 0,  4,  8, 12])

In [13]:
np.linspace(0, 20, 5)# آرایه‌ی یک بعدی شامل ۵ عدد حقیقی در بازه ۰ تا ۲۰ (شامل این دو) با فاصله برابر

array([ 0.,  5., 10., 15., 20.])

In [14]:
np.eye(3)# آرایه‌ی دو بعدی ۳*۳ متناظر با ماتریس همانی (قطر ۱ و باقی خانه‌ها ۰)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
np.empty(3)# آرایه‌ی یک بعدی شامل ۳ عدد نامشخص (بسته به مقدار داخل حافظه)

array([1., 1., 1.])

In [16]:
np.random.random(3)# آرایه‌ی یک بعدی شامل ۳ عدد تصادفی از توزیع یکنواخت بین ۰ و ۱

array([0.39072559, 0.27084824, 0.67662889])

In [17]:
np.random.randint(0, 10, (3, 3)) # آرایه‌ی دو بعدی ۳*۳ شامل اعداد صحیح تصادفی بین ۰ تا ۹

array([[8, 5, 0],
       [9, 2, 2],
       [4, 8, 5]])

In [18]:
np.random.normal(0, 1, (2, 3))# آرایه‌ی دو بعدی ۳*۲ شامل اعداد تصادفی از توزیع نرمال با میانگین ۰ و واریانس ۱

array([[ 1.48378662, -1.33953122, -0.26550882],
       [-0.14723005, -1.89870531, -0.99295058]])

In [19]:
a = np.random.randint(0, 10, (2, 3)) # آرایه‌ی دو بعدی ۳*۲ شامل اعداد صحیح تصادفی بین ۰ تا ۱۰ 
# آرایه‌ی پر از ۳ با ابعاد مشابه آرایه ورودی (۳*۲)
np.full_like(a, 3)

array([[3, 3, 3],
       [3, 3, 3]])

In [20]:
np.array([1, 2, 3.14], dtype='int_') # نوع عدد صحیح (عدد سوم تبدیل به 3 می‌شود)

array([1, 2, 3])

In [21]:
np.array([2.71828182845, 3.14159265359], dtype='float64') # نوع عدد حقیقی ۶۴ بیتی

array([2.71828183, 3.14159265])

In [22]:
np.array(['Hello', 'World'], dtype='str_') # نوع رشته

array(['Hello', 'World'], dtype='<U5')

In [23]:
a = np.array([[1, 2],
             [3, 4],
             [5, 6]], dtype='float64')
print(a)
print('number of dimensions:', a.ndim) # تعداد ابعاد آرایه
print('shape:', a.shape) # اندازه ابعاد آرایه
print('size:', a.size) # تعداد خانه‌های آرایه
print('dtype:', a.dtype) # نوع داده آرایه

[[1. 2.]
 [3. 4.]
 [5. 6.]]
number of dimensions: 2
shape: (3, 2)
size: 6
dtype: float64


In [24]:
c = np.array(['h', 'e', 'l', 'l', 'o'])
print(c)
print(c.itemsize, 'bytes') # تعداد بایت برای هر خانه آرایه
print(c.nbytes, 'bytes') # تعداد بایت برای کل آرایه

['h' 'e' 'l' 'l' 'o']
4 bytes
20 bytes
